# Gradle runtime options
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Java / Hytale options
java_version = 25
hytale_version = 0.5.7

# Mod identity
group = com.thewhiteninja.runningskeleton
manifest_group = TheWhiteNinja
mod_name = RunningSkeleton
main_class = com.thewhiteninja.runningskeleton.RunningSkeletonPlugin
mod_author = TheWhiteNinja
mod_id = RunningSkeleton
mod_license = MIT
mod_description = [1-2000] chance for a Skeleton to Run Across Your Screen (configurable)
mod_url = https://github.com/thewhiteninjas/RunningSkeletonMod
version = 1.0

# Manifest / packaging options
includes_pack = true
disabled_by_default = false
patchline = release
server_version = 0.5.7
manifestServerVersion = >=0.5.7 <0.6.0
manifest_dependencies = Hytale:AssetModule=*
manifest_opt_dependencies =
curseforgeID =
injectServerJavadocsIntoSources = true
generateAssetsBinary = false
